buildscript {
    configurations.all {
        resolutionStrategy {
            force("com.fasterxml.jackson.core:jackson-core:2.18.2")
        }
    }
}

plugins {
    `tbp-module`
    alias(libs.plugins.spotbugs)
}

repositories {
    mavenCentral()
    maven("https://repo.breweryteam.dev/mirror")
    maven("https://jitpack.io")
    maven("https://storehouse.okaeri.eu/repository/maven-public/")
}

dependencies {
    api(project(":api"))

    // libraries
    compileOnly(libs.sqlite.jdbc)
    compileOnly(libs.guava)
    compileOnly(libs.gson)
    compileOnly(libs.joml)
    compileOnly(libs.adventure.api)
    compileOnly(libs.adventure.text.minimessage)
    api(libs.okaeri.yaml)
    implementation(libs.simple.yaml) {
        exclude("org.yaml", "snakeyaml")
    }
    implementation(libs.hikaricp)
    implementation(libs.exp4j)

    // other
    compileOnly(libs.jetbrains.annotations)

    // test
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)

    testImplementation(testFixtures(project(":api")))
    testImplementation(libs.gson)
    testImplementation(libs.joml)
    testImplementation(libs.guava)
    testImplementation(libs.sqlite.jdbc)
    testImplementation(libs.adventure.api)
    spotbugs(libs.spotbugs)
}

tasks {
    processResources {
        dependsOn(project(":datagenerator").getTasksByName("run", false))
    }

    test {
        useJUnitPlatform()
    }
}

sourceSets {
    main {
        resources.srcDir(file("src/autogenerated/resources"))
    }
}

spotbugs {
    excludeFilter = file("${rootProject.projectDir}/spotbugs-filter.xml")
}





