plugins {
    application

    alias(libs.plugins.neoforged.gradle.common)
    alias(libs.plugins.spotbugs)
}

group = "dev.jsinco.brewery.datagenerator"
version = project.findProperty("version")!!

repositories {
    mavenCentral()
    maven("https://repo.breweryteam.dev/mirror")
    maven("https://maven.neoforged.net/releases")
}

dependencies {
    implementation("net.minecraft:client:${project.findProperty("minecraft.version")!!}:client-extra")
    implementation(libs.gson)
    implementation(libs.jspecify)
    spotbugs(libs.spotbugs)
}

java.toolchain {
    languageVersion = JavaLanguageVersion.of(21)
}

tasks {
    application {
        mainClass = "dev.jsinco.brewery.datagenerator.DataGenerator"
    }

    getByName<JavaExec>("run") {
        args = listOf(rootProject.projectDir.resolve("core/src/autogenerated/resources").absolutePath)
    }
}

spotbugs {
    excludeFilter = file("${rootProject.projectDir}/spotbugs-filter.xml")
}